### ISSUE TITLE
生成的样本有些奇怪

### ISSUE THREAD

**Issue by Pro-flynn** [wang-tf/Chinese_OCR_synthetic_data#2]
楼主你好 有个问题咨询一下
我生成的样本有些奇怪
![14pmingliu_0](https://user-images.githubusercontent.com/25923129/62945832-14d98800-be12-11e9-86a9-8ee41e0a166a.jpg)
汉字的端点处的墨太多了
我的字体是下图
![image](https://user-images.githubusercontent.com/25923129/62945924-47838080-be12-11e9-8d6e-957f120cbd70.png)

作者遇到过这个问题吗 还望提点

**Comment by wang-tf** [comment]
没有遇到过这种情况。是某些字生成的奇怪还是所有这个字体生成的字都奇怪呢？我的建议是，你可以试试生成一个“中国智造”的图片看看，如果没有问题，说明是字体库中某些字会显示异常；如果问题存在，说明这个字体的显示效果存在问题，可以试试下载其他字体或换个平台和代码语言试试。
