### ISSUE TITLE
这个到底是合成识别数据集，还是检测+识别的数据集？？

### ISSUE THREAD

**Issue by lmw0320** [wang-tf/Chinese_OCR_synthetic_data#5]
我看了下sample图片，貌似只是合成识别部分的数据集？？
如果是要合成检测 + 识别文本的数据集，即包含文本框的坐标信息，是否可以？？？
另外，我想合成的文本，不仅仅包含水平文本，还要包含环形文本（带文本框坐标数据），是否可以？？？

**Comment by wang-tf** [comment]
是的，不包含坐标框，不包含环形文本。建议自行添加相应功能。
________________________________
发件人: lmw0320 <notifications@github.com>
发送时间: 2020年11月4日 6:47
收件人: wang-tf/Chinese_OCR_synthetic_data <Chinese_OCR_synthetic_data@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wang-tf/Chinese_OCR_synthetic_data] 这个到底是合成识别数据集，还是检测+识别的数据集？？ (#5)


我看了下sample图片，貌似只是合成识别部分的数据集？？
如果是要合成检测 + 识别文本的数据集，即包含文本框的坐标信息，是否可以？？？
另外，我想合成的文本，不仅仅包含水平文本，还要包含环形文本（带文本框坐标数据），是否可以？？？

―

**Comment by lmw0320** [comment]
如何自行添加功能，这个要自己写代码啊，不是简单地设置参数。。
这两个问题，又是难点。。。

**Comment by wang-tf** [comment]
抱歉，这个仓库目前没有增加功能的计划。建议寻找一些具有相关功能的仓库。
