### ISSUE TITLE
关于synthetic数据集

### ISSUE THREAD

**Issue by Saiga-fire** [wang-tf/Chinese_OCR_synthetic_data#6]
hello，大佬，有个问题想请教下：
sythetic数据集是关于图像处理的吗？
从哪里能找到这个数据集呢？
拜托啦！

**Comment by wang-tf** [comment]
并不是数据集。这只是一个合成工具，通过输入文本和图像和合成各种风格的图片。

**Comment by Saiga-fire** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
